package org.ex.exceptionalvision.world;

import net.minecraft.nbt.CompoundTag;
import org.ex.exceptionalvision.ExceptionalVision;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.PriorityBlockingQueue;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * Background file-I/O queue for reading region files, decoupled from both the
 * LOD downsampling thread pool and the render thread. See
 * {@code 05_world_data_ingestion.md} ("Многопоточная организация").
 * <p>
 * Regions closer to the player should be submitted with a lower {@code priority}
 * value (processed first); {@link #submitLowPriority(Path)} is used for
 * background/full-world imports (e.g. picking up chunks pregenerated by Chunky).
 */
public final class RegionImportQueue implements AutoCloseable {

    /** Priority used for the full-world / background import path. */
    public static final int LOW_PRIORITY = Integer.MAX_VALUE;

    private record Task(RegionCoordinate coordinate, Path mcaFile, int priority, long sequence)
            implements Comparable<Task> {
        @Override
        public int compareTo(Task other) {
            int byPriority = Integer.compare(priority, other.priority);
            return byPriority != 0 ? byPriority : Long.compare(sequence, other.sequence);
        }
    }

    private final RegionFileReader reader = new RegionFileReader();
    private final PriorityBlockingQueue<Task> queue = new PriorityBlockingQueue<>();
    private final ExecutorService ioExecutor;
    private final Consumer<RegionResult> onRegionRead;
    private final AtomicInteger sequenceCounter = new AtomicInteger();
    private volatile boolean running = true;

    /**
     * @param ioThreads    number of background I/O threads (spec recommends 2 — enough
     *                     to keep disk busy without starving downsampling/render threads)
     * @param onRegionRead invoked (off the caller's thread) once a region's chunks have
     *                     been read; hands raw column data to the LOD Builder (stage 2)
     */
    public RegionImportQueue(int ioThreads, Consumer<RegionResult> onRegionRead) {
        this.onRegionRead = onRegionRead;
        this.ioExecutor = Executors.newFixedThreadPool(ioThreads, runnable -> {
            Thread thread = new Thread(runnable, "exceptional-vision-region-io");
            thread.setDaemon(true);
            return thread;
        });
        for (int i = 0; i < ioThreads; i++) {
            ioExecutor.submit(this::workerLoop);
        }
    }

    /** Submits a single region for reading at the given priority (lower = sooner). */
    public void submit(Path mcaFile, int priority) {
        RegionCoordinate coordinate = RegionCoordinate.fromFileName(mcaFile.getFileName().toString())
                .orElse(null);
        if (coordinate == null) {
            ExceptionalVision.LOGGER.warn("Skipping file with unexpected name: {}", mcaFile);
            return;
        }
        queue.put(new Task(coordinate, mcaFile, priority, sequenceCounter.incrementAndGet()));
    }

    /** Submits a region at background/full-world-import priority. */
    public void submitLowPriority(Path mcaFile) {
        submit(mcaFile, LOW_PRIORITY);
    }

    /**
     * Queues every existing region file in {@code <world>/region} (or an arbitrary
     * region directory) for low-priority processing — the independent equivalent of
     * "import the whole world", including territory pregenerated by Chunky that the
     * player has never actually visited. See {@code 05_world_data_ingestion.md}.
     */
    public void queueFullWorldImport(Path regionDir) throws IOException {
        if (!Files.isDirectory(regionDir)) {
            ExceptionalVision.LOGGER.warn("Region directory does not exist: {}", regionDir);
            return;
        }
        try (Stream<Path> files = Files.list(regionDir)) {
            files.filter(p -> p.toString().endsWith(".mca")).forEach(this::submitLowPriority);
        }
    }

    private void workerLoop() {
        while (running) {
            Task task;
            try {
                task = queue.take();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
            processTask(task);
        }
    }

    private void processTask(Task task) {
        try {
            List<ChunkHeightData> chunks = new ArrayList<>(32 * 32);
            for (int localZ = 0; localZ < 32; localZ++) {
                for (int localX = 0; localX < 32; localX++) {
                    CompoundTag chunkNbt = reader.readChunk(task.mcaFile(), localX, localZ);
                    if (chunkNbt == null) {
                        continue; // not generated
                    }
                    chunks.add(reader.extractHeightData(chunkNbt));
                }
            }
            onRegionRead.accept(new RegionResult(task.coordinate(), chunks));
        } catch (IOException e) {
            ExceptionalVision.LOGGER.warn("Failed to read region file {}: {}", task.mcaFile(), e.toString());
        } catch (RuntimeException e) {
            // Defensive: a single malformed chunk/section must not kill the worker thread.
            ExceptionalVision.LOGGER.error("Unexpected error processing region file {}", task.mcaFile(), e);
        }
    }

    @Override
    public void close() {
        running = false;
        ioExecutor.shutdownNow();
    }
}
