package org.ex.exceptionalvision.world;

import net.minecraft.nbt.CompoundTag;
import org.ex.exceptionalvision.ExceptionalVision;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.PriorityBlockingQueue;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * Background file-I/O queue for reading region files, decoupled from both the
 * LOD downsampling thread pool and the render thread. See
 * {@code 05_world_data_ingestion.md} ("Многопоточная организация").
 * <p>
 * Regions closer to the player should be submitted with a lower {@code priority}
 * value (processed first); {@link #submitLowPriority(Path)} is used for
 * background/full-world imports (e.g. picking up chunks pregenerated by Chunky).
 */
public final class RegionImportQueue implements AutoCloseable {

    /** Priority used for the full-world / background import path. */
    public static final int LOW_PRIORITY = Integer.MAX_VALUE;

    private record Task(RegionCoordinate coordinate, Path mcaFile, int priority, long sequence)
            implements Comparable<Task> {
        @Override
        public int compareTo(Task other) {
            int byPriority = Integer.compare(priority, other.priority);
            return byPriority != 0 ? byPriority : Long.compare(sequence, other.sequence);
        }
    }

    // FIX: an IOException here (almost always EOFException from a region file that's
    // mid-write - a header/sector not fully flushed yet) used to be a silent, permanent
    // drop: the task was logged and discarded, with nothing left to ever retry it unless
    // WorldDirectoryWatcher happened to fire another event for that exact file. In
    // practice (e.g. a separate bulk chunk-pregeneration mod writing many region files
    // back-to-back) that reliably meant "most regions never get a single successful
    // read all session" - confirmed by a real run where every region but one failed this
    // way and was never retried. A few short, capped retries turns "file caught mid-write"
    // back into "processed a little late" instead of "never processed".
    private static final int MAX_READ_RETRIES = 5;
    private static final long RETRY_DELAY_MS = 750;

    private final java.util.Map<Path, Integer> readRetryCounts = new ConcurrentHashMap<>();
    private final ScheduledExecutorService retryScheduler = Executors.newSingleThreadScheduledExecutor(runnable -> {
        Thread thread = new Thread(runnable, "exceptional-vision-region-io-retry");
        thread.setDaemon(true);
        return thread;
    });

    private final RegionFileReader reader = new RegionFileReader();
    private final PriorityBlockingQueue<Task> queue = new PriorityBlockingQueue<>();
    private final ExecutorService ioExecutor;
    private final Consumer<RegionResult> onRegionRead;
    private final AtomicInteger sequenceCounter = new AtomicInteger();
    private volatile boolean running = true;

    /**
     * @param ioThreads    number of background I/O threads (spec recommends 2 — enough
     *                     to keep disk busy without starving downsampling/render threads)
     * @param onRegionRead invoked (off the caller's thread) once a region's chunks have
     *                     been read; hands raw column data to the LOD Builder (stage 2)
     */
    public RegionImportQueue(int ioThreads, Consumer<RegionResult> onRegionRead) {
        this.onRegionRead = onRegionRead;
        this.ioExecutor = Executors.newFixedThreadPool(ioThreads, runnable -> {
            Thread thread = new Thread(runnable, "exceptional-vision-region-io");
            thread.setDaemon(true);
            return thread;
        });
        for (int i = 0; i < ioThreads; i++) {
            ioExecutor.submit(this::workerLoop);
        }
    }

    /** Submits a single region for reading at the given priority (lower = sooner). */
    public void submit(Path mcaFile, int priority) {
        RegionCoordinate coordinate = RegionCoordinate.fromFileName(mcaFile.getFileName().toString())
                .orElse(null);
        if (coordinate == null) {
            ExceptionalVision.LOGGER.warn("Skipping file with unexpected name: {}", mcaFile);
            return;
        }
        queue.put(new Task(coordinate, mcaFile, priority, sequenceCounter.incrementAndGet()));
    }

    /** Submits a region at background/full-world-import priority. */
    public void submitLowPriority(Path mcaFile) {
        submit(mcaFile, LOW_PRIORITY);
    }

    /**
     * Queues every existing region file in {@code <world>/region} (or an arbitrary
     * region directory) for low-priority processing — the independent equivalent of
     * "import the whole world", including territory pregenerated by Chunky that the
     * player has never actually visited. See {@code 05_world_data_ingestion.md}.
     */
    public void queueFullWorldImport(Path regionDir) throws IOException {
        if (!Files.isDirectory(regionDir)) {
            ExceptionalVision.LOGGER.warn("Region directory does not exist: {}", regionDir);
            return;
        }
        try (Stream<Path> files = Files.list(regionDir)) {
            files.filter(p -> p.toString().endsWith(".mca")).forEach(this::submitLowPriority);
        }
    }

    private void workerLoop() {
        while (running) {
            Task task;
            try {
                task = queue.take();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
            processTask(task);
        }
    }

    private void processTask(Task task) {
        try {
            List<ChunkHeightData> chunks = new ArrayList<>(32 * 32);
            for (int localZ = 0; localZ < 32; localZ++) {
                for (int localX = 0; localX < 32; localX++) {
                    CompoundTag chunkNbt = reader.readChunk(task.mcaFile(), localX, localZ);
                    if (chunkNbt == null) {
                        continue; // not generated
                    }
                    chunks.add(reader.extractHeightData(chunkNbt));
                }
            }
            readRetryCounts.remove(task.mcaFile()); // this file is fine now, forget any earlier failures
            onRegionRead.accept(new RegionResult(task.coordinate(), chunks));
        } catch (IOException e) {
            retryOrGiveUp(task, e);
        } catch (RuntimeException e) {
            // Defensive: a single malformed chunk/section must not kill the worker thread.
            ExceptionalVision.LOGGER.error("Unexpected error processing region file {}", task.mcaFile(), e);
        }
    }

    /**
     * Re-queues {@code task} after a short delay, up to {@link #MAX_READ_RETRIES} times,
     * instead of dropping it after the first failure - see the field javadoc above for
     * why. Retries run through the same {@link #queue}/worker pool as any other task (at
     * the task's original priority), the scheduler here only provides the delay.
     */
    private void retryOrGiveUp(Task task, IOException cause) {
        int attempt = readRetryCounts.merge(task.mcaFile(), 1, Integer::sum);
        if (!running || attempt > MAX_READ_RETRIES) {
            ExceptionalVision.LOGGER.warn("Failed to read region file {} after {} attempt(s), giving up for this session: {}",
                    task.mcaFile(), attempt, cause.toString());
            return;
        }
        ExceptionalVision.LOGGER.debug("Region file {} not ready yet (attempt {}/{}): {} - retrying in {}ms",
                task.mcaFile(), attempt, MAX_READ_RETRIES, cause.toString(), RETRY_DELAY_MS);
        retryScheduler.schedule(() -> {
            if (running) {
                queue.put(new Task(task.coordinate(), task.mcaFile(), task.priority(), sequenceCounter.incrementAndGet()));
            }
        }, RETRY_DELAY_MS, TimeUnit.MILLISECONDS);
    }

    @Override
    public void close() {
        running = false;
        ioExecutor.shutdownNow();
        retryScheduler.shutdownNow();
    }
}